{
    "openapi": "3.0.0",
    "info": {
        "title": "Sent SKUs",
        "description": "Collection composed by requests for the VTEX Sent SKUs API, used by channels integrations for providing visibility to the sellers and turn easier to sell on channels.",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://portal.vtexcommercestable.com.br",
            "description": "VTEX server url"
        }
    ],
    "paths": {
        "/api/productfeed/config": {
            "get": {
                "tags": [
                    "Settings"
                ],
                "summary": "Retrieve channels",
                "description": "Retrieve channels using the product feed",
                "operationId": "retrieveChannels",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/config": {
            "post": {
                "tags": [
                    "Settings"
                ],
                "summary": "Create channel",
                "description": "Create a channel at the product feed",
                "operationId": "createChannel",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateChannel"
                            },
                            "example": {
                                "notificationEndpoint": "http://skyhubintegration.vtexinternal.com/api/skyhubintegration/commercialcondition?an=philco",
                                "salesPolicy": "1",
                                "name": "B2W",
                                "logoUrl": "https://s3.amazonaws.com/Marketplace-Integration/Bridge/logos/skyhub.png"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/workflow": {
            "get": {
                "tags": [
                    "History"
                ],
                "summary": "Search logs in history",
                "description": "",
                "operationId": "searchLogsInHistory",
                "parameters": [
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "orderBy",
                        "in": "query",
                        "required": true,
                        "description": "",
                        "schema": {
                            "type": "string",
                            "default": "creationDate,desc"
                        }
                    },
                    {
                        "name": "offset",
                        "in": "query",
                        "required": false,
                        "description": "",
                        "schema": {
                            "type": "integer",
                            "format": "int32",
                            "minimum": 0,
                            "example": "0"
                        }
                    },
                    {
                        "name": "limit",
                        "in": "query",
                        "required": false,
                        "description": "Limit of logs returned on each page.",
                        "schema": {
                            "type": "integer",
                            "format": "int32",
                            "minimum": 1,
                            "example": "15"
                        }
                    },
                    {
                        "name": "feedId",
                        "in": "query",
                        "required": false,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "required": false,
                        "description": "Status of the logs being searched",
                        "schema": {
                            "type": "string",
                            "default": "success"
                        }
                    },
                    {
                        "name": "flag",
                        "in": "query",
                        "required": false,
                        "description": "",
                        "schema": {
                            "type": "string",
                            "default": ""
                        }
                    },
                    {
                        "name": "type",
                        "in": "query",
                        "required": false,
                        "description": "",
                        "schema": {
                            "type": "string",
                            "default": ""
                        }
                    },
                    {
                        "name": "search",
                        "in": "query",
                        "required": false,
                        "description": "Search term. Can be used to look for a SKU ID or EAN.",
                        "schema": {
                            "type": "string",
                            "default": "123"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/workflow/facets": {
            "get": {
                "tags": [
                    "History"
                ],
                "summary": "Retrieve history facets",
                "description": "",
                "operationId": "historyFacets",
                "parameters": [
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/{feedId}/workflow": {
            "post": {
                "tags": [
                    "History"
                ],
                "summary": "Create log",
                "description": "Creates a log at the history",
                "operationId": "createLog",
                "parameters": [
                    {
                        "name": "feedId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateLogRequest"
                            },
                            "example": {
                                "skuId": "310117351",
                                "marketplaceSkuId": "310117351",
                                "currency": "BRL",
                                "mainImageUrl": "",
                                "skuName": "Produto Vtex teste branca m",
                                "creationDate": "2020-03-27T14:04:27.1320848+00:00",
                                "type": "Marketplace",
                                "flag": "Price",
                                "value": 10,
                                "EAN": "9900004712767"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/{feedId}/workflow/{logId}/status": {
            "put": {
                "tags": [
                    "History"
                ],
                "summary": "Update log status",
                "description": "Updates the status of a log",
                "operationId": "updateStatus",
                "parameters": [
                    {
                        "name": "feedId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "logId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the log.",
                        "schema": {
                            "type": "string",
                            "default": "123972365"
                        }
                    },
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateLogRequest"
                            },
                            "example": {
                                "status": "Success"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/{feedId}/workflow/{logId}": {
            "get": {
                "tags": [
                    "History"
                ],
                "summary": "Retrieve log info",
                "description": "Retrieve all informations about a specific log",
                "operationId": "retrieveLog",
                "parameters": [
                    {
                        "name": "feedId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "logId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the log.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/{feedId}/workflow/{logId}/entry": {
            "post": {
                "tags": [
                    "History"
                ],
                "summary": "Create notification",
                "description": "Creates a notification inside a log",
                "operationId": "createNotification",
                "parameters": [
                    {
                        "name": "feedId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "logId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the log.",
                        "schema": {
                            "type": "string",
                            "default": "123972365"
                        }
                    },
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateNotificationRequest"
                            },
                            "example": {
                                "message": "Preço alterado na VTEX",
                                "eventDate": "2020-03-27T13:04:27.1627612+00:00",
                                "status": "Success",
                                "agent": "Broadcaster",
                                "evidence": {
                                    "request": "POST https://www.vtex.com",
                                    "response": "200 Ok"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/{feedId}/workflow/{logId}/entry/{notificationId}": {
            "get": {
                "tags": [
                    "History"
                ],
                "summary": "Retrieves notification info",
                "description": "",
                "operationId": "retrieveNotification",
                "parameters": [
                    {
                        "name": "feedId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "jkasdq7e62"
                        }
                    },
                    {
                        "name": "logId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the feed.",
                        "schema": {
                            "type": "string",
                            "default": "123972365"
                        }
                    },
                    {
                        "name": "notificationId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the notification.",
                        "schema": {
                            "type": "string",
                            "default": "9823jbqww"
                        }
                    },
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        },
        "/api/productfeed/workflow/entry/evidence/{evidenceId}": {
            "get": {
                "tags": [
                    "History"
                ],
                "summary": "Retrieves evidence info",
                "description": "",
                "operationId": "retrieveEvidence",
                "parameters": [
                    {
                        "name": "evidenceId",
                        "in": "path",
                        "required": true,
                        "description": "Identifier of the evidence.",
                        "schema": {
                            "type": "string",
                            "default": "asjdq7we6we"
                        }
                    },
                    {
                        "name": "an",
                        "in": "query",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "lojadomatheus"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false
            }
        }
    },
    "components": {
        "schemas": {
            "CreateChannel": {
                "title": "CreateChannel",
                "required": [
                    "notificationEndpoint",
                    "salesPolicy",
                    "name",
                    "logoUrl"
                ],
                "type": "object",
                "properties": {
                    "notificationEndpoint": {
                        "type": "string"
                    },
                    "salesPolicy": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "logoUrl": {
                        "type": "string"
                    }
                },
                "example": {
                    "notificationEndpoint": "http://skyhubintegration.vtexinternal.com/api/skyhubintegration/commercialcondition?an=philco",
                    "salesPolicy": "1",
                    "name": "B2W",
                    "logoUrl": "https://s3.amazonaws.com/Marketplace-Integration/Bridge/logos/skyhub.png"
                }
            },
            "CreateNotificationRequest": {
                "title": "CreateNotificationRequest",
                "required": [
                    "message",
                    "eventDate",
                    "status",
                    "agent",
                    "evidence"
                ],
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    },
                    "eventDate": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "agent": {
                        "type": "string"
                    },
                    "evidence": {
                        "type": "object",
                        "properties": {
                            "request": {
                                "type": "string"
                            },
                            "response": {
                                "type": "string"
                            }
                        },
                        "description": ""
                    }
                },
                "example": {
                    "message": "Preço alterado na VTEX",
                    "eventDate": "2020-03-27T13:04:27.1627612+00:00",
                    "status": "Success",
                    "agent": "Broadcaster",
                    "evidence": {
                        "request": "POST https://www.vtex.com",
                        "response": "200 Ok"
                    }
                }
            },
            "UpdateLogRequest": {
                "title": "UpdateLogRequest",
                "required": [
                    "status"
                ],
                "type": "object",
                "properties": {
                    "status": {
                        "type": "string"
                    }
                },
                "example": {
                    "status": "Success"
                }
            },
            "CreateLogRequest": {
                "title": "CreateLogRequest",
                "required": [
                    "skuId",
                    "marketplaceSkuId",
                    "currency",
                    "mainImageUrl",
                    "skuName",
                    "creationDate",
                    "type",
                    "flag",
                    "value",
                    "EAN"
                ],
                "type": "object",
                "properties": {
                    "skuId": {
                        "type": "string"
                    },
                    "marketplaceSkuId": {
                        "type": "string"
                    },
                    "currency": {
                        "type": "string"
                    },
                    "mainImageUrl": {
                        "type": "string"
                    },
                    "skuName": {
                        "type": "string"
                    },
                    "creationDate": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "flag": {
                        "type": "string"
                    },
                    "value": {
                        "type": "string"
                    },
                    "EAN": {
                        "type": "string"
                    }
                },
                "example": {
                    "skuId": "310117351",
                    "marketplaceSkuId": "310117351",
                    "currency": "BRL",
                    "mainImageUrl": "",
                    "skuName": "Produto Vtex teste branca m",
                    "creationDate": "2020-03-27T14:04:27.1320848+00:00",
                    "type": "Marketplace",
                    "flag": "Price",
                    "value": 10,
                    "EAN": "9900004712767"
                }
            }
        },
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey"
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken"
            }
        }
    },
    "tags": [
        {
            "name": "History",
            "description": "Detailed timeline of all logs and notifications."
        }
    ],
    "security": [
        {
            "appKey": [],
            "appToken": []
        }
    ]
}
