{
    "openapi": "3.0.0",
    "info": {
        "title": "Pricing Hub ",
        "description": "Pricing Hub canonical route",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://prchub.{enviroment}.com.br",
            "description": "VTEX server url"
        }
    ],
    "paths": {
        "/api/pricing-hub/prices?an={accountName}": {
            "post": {
                "tags": [
                    "Pricing Hub"
                ],
                "summary": "Proxy",
                "description": "Link between Checkout and Pricing",
                "parameters": [
                    {
                        "name": "accountName",
                        "in": "path",
                        "required": true,
                        "description": "Name of the VTEX account. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "apiexamples"
                        }
                    },
                    {
                        "name": "environment",
                        "in": "path",
                        "required": true,
                        "description": "Environment to use. Used as part of the URL",
                        "schema": {
                            "type": "string",
                            "default": "vtexcommercestable"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "title": "Request body",
                                "default": {},
                                "required": [
                                    "Items",
                                    "SalesChannel"
                                ],
                                "properties": {
                                    "items": {
                                        "type": "array",
                                        "title": "fixedPrices",
                                        "description": "List of items",
                                        "default": [],
                                        "required": [
                                            "minQuantity",
                                            "value",
                                            "tradePolicyId"
                                        ],
                                        "properties": {
                                            "tradePolicyId": {
                                                "type": "string",
                                                "title": "tradePolicyId",
                                                "description": "Trade Policy Id",
                                                "default": ""
                                            },
                                            "value": {
                                                "type": "number",
                                                "title": "value",
                                                "description": "Price"
                                            },
                                            "listPrice": {
                                                "type": "number",
                                                "title": "listPrice",
                                                "description": "SKU List Fixed Price"
                                            },
                                            "minQuantity": {
                                                "type": "integer",
                                                "title": "minQuantity",
                                                "description": "Minimum quantity of the SKU"
                                            },
                                            "dateRange": {
                                                "type": "object",
                                                "title": "dateRange",
                                                "description": "Trade Policy Fixed Price Validity Period Object",
                                                "default": {},
                                                "required": [
                                                    "from",
                                                    "to"
                                                ],
                                                "properties": {
                                                    "from": {
                                                        "type": "string",
                                                        "title": "from",
                                                        "description": "Validity start Date",
                                                        "default": ""
                                                    },
                                                    "to": {
                                                        "type": "string",
                                                        "title": "to",
                                                        "description": "Validity end Date",
                                                        "default": ""
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    "utmSource": {
                                        "type": "number",
                                        "title": "listPrice",
                                        "description": "SKU List Price",
                                        "default": 12
                                    },
                                    "utmMedium": {
                                        "type": "number",
                                        "title": "basePrice",
                                        "description": "SKU Selling Base Price",
                                        "default": 100
                                    },
                                    "utmCampaign": {
                                        "type": "number",
                                        "title": "utmCampaign",
                                        "description": ""
                                    },
                                    "salesChannel": {
                                        "type": "string",
                                        "title": "utmCampaign",
                                        "description": "salesChannel ID",
                                        "default": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Examplewith2FixedPricesindifferentSalesChannel": {
                "title": "Examplewith2FixedPricesindifferentSalesChannel",
                "required": [
                    "tradePolicyId",
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string"
                    },
                    "value": {
                        "type": "number"
                    },
                    "listPrice": {
                        "type": "number",
                        "nullable": true
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "tradePolicyId": "6",
                    "value": 20.9,
                    "listPrice": 22.9,
                    "minQuantity": 1
                }
            },
            "Create/EditFixedPriceRequest": {
                "title": "Create/EditFixedPriceRequest",
                "required": [
                    "listPrice",
                    "costPrice",
                    "markup",
                    "fixedPrices"
                ],
                "type": "object",
                "properties": {
                    "listPrice": {
                        "type": "integer",
                        "format": "int32",
                        "description": "SKU List Price"
                    },
                    "costPrice": {
                        "type": "integer",
                        "format": "int32",
                        "description": "SKU Cost Price"
                    },
                    "markup": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "basePrice": {
                        "type": "integer",
                        "format": "int32",
                        "description": "SKU Selling Base Price"
                    },
                    "fixedPrices": {
                        "type": "array",
                        "description": "SKU Fixed Prices Object",
                        "items": {
                            "$ref": "#/components/schemas/FixedPrice"
                        }
                    }
                }
            },
            "FixedPrice": {
                "title": "FixedPrice",
                "required": [
                    "tradePolicyId",
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string",
                        "description": "Sales Channel Id"
                    },
                    "value": {
                        "type": "integer",
                        "format": "int32",
                        "description": "SKU Fixed Price Value"
                    },
                    "listPrice": {
                        "type": "integer",
                        "nullable": true,
                        "description": "SKU List Price"
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32",
                        "description": "Minimum Quantity to active Fixed Price"
                    },
                    "dateRange": {
                        "description": "Trade Policy Fixed Price Validity Period Object",
                        "$ref": "#/components/schemas/DateRange",
                        "type": "object"
                    }
                },
                "example": {
                    "tradePolicyId": "9",
                    "value": 300,
                    "listPrice": null,
                    "minQuantity": 1
                }
            },
            "DateRange": {
                "title": "DateRange",
                "required": [
                    "from",
                    "to"
                ],
                "type": "object",
                "properties": {
                    "from": {
                        "type": "string",
                        "description": "Validity start Date"
                    },
                    "to": {
                        "type": "string",
                        "description": "Validity end Date"
                    }
                },
                "example": {
                    "from": "2017-12-07T14:30:00Z",
                    "to": "2017-12-30T14:30:00Z"
                }
            },
            "Create/EditFixedPricesonapricetable_ortradepolicy_Request": {
                "title": "Create/EditFixedPricesonapricetable(ortradepolicy)Request",
                "required": [
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "value": {
                        "type": "number"
                    },
                    "listPrice": {
                        "type": "number"
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "value": 60.5,
                    "listPrice": 90.5,
                    "minQuantity": 1
                }
            },
            "Addingafixedpriceforonespecificpricetable": {
                "title": "Addingafixedpriceforonespecificpricetable",
                "required": [
                    "tradePolicyId",
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string"
                    },
                    "value": {
                        "type": "number"
                    },
                    "listPrice": {
                        "type": "string",
                        "nullable": true
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "tradePolicyId": "10",
                    "value": 60.5,
                    "listPrice": null,
                    "minQuantity": 1
                }
            },
            "SchedulingFixedPricesRequest": {
                "title": "SchedulingFixedPricesRequest",
                "required": [
                    "listPrice",
                    "costPrice",
                    "markup",
                    "fixedPrices"
                ],
                "type": "object",
                "properties": {
                    "listPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "costPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "markup": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "fixedPrices": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/FixedPrice"
                        },
                        "description": ""
                    }
                }
            },
            "Deletefixedpricesonapricetable_ortradepolicy_Request": {
                "title": "Deletefixedpricesonapricetable(ortradepolicy)Request",
                "required": [
                    "tradePolicyId",
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string"
                    },
                    "value": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "listPrice": {
                        "type": "number"
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "tradePolicyId": "1",
                    "value": 100,
                    "listPrice": 99.9,
                    "minQuantity": 1
                }
            },
            "PricewithFixedPrices_scheduledandindifferenttradepolicies_": {
                "title": "PricewithFixedPrices(scheduledandindifferenttradepolicies)",
                "required": [
                    "itemId",
                    "listPrice",
                    "costPrice",
                    "markup",
                    "basePrice",
                    "fixedPrices"
                ],
                "type": "object",
                "properties": {
                    "itemId": {
                        "type": "string"
                    },
                    "listPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "costPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "markup": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "basePrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "fixedPrices": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/FixedPrice2"
                        },
                        "description": ""
                    }
                },
                "example": {
                    "itemId": "1234512354",
                    "listPrice": 300,
                    "costPrice": 10,
                    "markup": 2400,
                    "basePrice": 250,
                    "fixedPrices": [
                        {
                            "tradePolicyId": "1",
                            "value": 666.66,
                            "listPrice": null,
                            "minQuantity": 1
                        },
                        {
                            "tradePolicyId": "9",
                            "value": 4500,
                            "listPrice": null,
                            "minQuantity": 1
                        },
                        {
                            "tradePolicyId": "9",
                            "value": 600,
                            "listPrice": null,
                            "minQuantity": 1,
                            "dateRange": {
                                "from": "2017-12-07T14:30:00Z",
                                "to": "2017-12-30T14:30:00Z"
                            }
                        },
                        {
                            "tradePolicyId": "9",
                            "value": 5555.55,
                            "listPrice": null,
                            "minQuantity": 1,
                            "dateRange": {
                                "from": "2017-12-20T14:30:00Z",
                                "to": "2017-12-22T14:30:00Z"
                            }
                        },
                        {
                            "tradePolicyId": "9",
                            "value": 555.55,
                            "listPrice": null,
                            "minQuantity": 1,
                            "dateRange": {
                                "from": "2017-12-06T15:00:00Z",
                                "to": "2017-12-14T15:00:00Z"
                            }
                        },
                        {
                            "tradePolicyId": "10",
                            "value": 5555.55,
                            "listPrice": null,
                            "minQuantity": 1
                        },
                        {
                            "tradePolicyId": "18",
                            "value": 555.55,
                            "listPrice": null,
                            "minQuantity": 1
                        }
                    ]
                }
            },
            "FixedPrice2": {
                "title": "FixedPrice2",
                "required": [
                    "tradePolicyId",
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string"
                    },
                    "value": {
                        "type": "number"
                    },
                    "listPrice": {
                        "type": "string",
                        "nullable": true
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "dateRange": {
                        "$ref": "#/components/schemas/DateRange"
                    }
                },
                "example": {
                    "tradePolicyId": "1",
                    "value": 666.66,
                    "listPrice": null,
                    "minQuantity": 1
                }
            },
            "Default": {
                "title": "Default",
                "required": [
                    "tradePolicyId",
                    "value",
                    "listPrice",
                    "minQuantity"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string"
                    },
                    "value": {
                        "type": "number"
                    },
                    "listPrice": {
                        "type": "number",
                        "nullable": true
                    },
                    "minQuantity": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "example": {
                    "tradePolicyId": "6",
                    "value": 20.9,
                    "listPrice": 22.9,
                    "minQuantity": 1
                }
            },
            "Default1": {
                "title": "Default1",
                "required": [
                    "tradePolicyId",
                    "listPrice",
                    "sellingPrice",
                    "priceValidUntil"
                ],
                "type": "object",
                "properties": {
                    "tradePolicyId": {
                        "type": "string"
                    },
                    "listPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "sellingPrice": {
                        "type": "number"
                    },
                    "priceValidUntil": {
                        "type": "string"
                    }
                },
                "example": {
                    "tradePolicyId": "1",
                    "listPrice": 30,
                    "sellingPrice": 18.9,
                    "priceValidUntil": "2018-12-20T18:12:14Z"
                }
            },
            "Create/EditPriceRequest": {
                "title": "Create/EditPriceRequest",
                "required": [
                    "listPrice",
                    "costPrice",
                    "markup",
                    "fixedPrices"
                ],
                "type": "object",
                "properties": {
                    "listPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "costPrice": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "markup": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "fixedPrices": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/FixedPrice"
                        },
                        "description": ""
                    }
                }
            },
            "Default2": {
                "title": "Default2",
                "required": [
                    "hasMigrated",
                    "migrationCurrentSKUIndex",
                    "migrationTotalSKU",
                    "defaultMarkup",
                    "minimumMarkups"
                ],
                "type": "object",
                "properties": {
                    "hasMigrated": {
                        "type": "boolean"
                    },
                    "migrationCurrentSKUIndex": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "migrationTotalSKU": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "defaultMarkup": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "minimumMarkups": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                },
                "example": {
                    "hasMigrated": true,
                    "migrationCurrentSKUIndex": 5200,
                    "migrationTotalSKU": 5200,
                    "defaultMarkup": 100,
                    "minimumMarkups": {
                        "1": 100,
                        "2": 90
                    }
                }
            },
            "Default3": {
                "title": "Default3",
                "required": [
                    "isActive",
                    "hasMigrated"
                ],
                "type": "object",
                "properties": {
                    "isActive": {
                        "type": "boolean"
                    },
                    "hasMigrated": {
                        "type": "boolean"
                    }
                },
                "example": {
                    "isActive": true,
                    "hasMigrated": true
                }
            }
        },
        "securitySchemes": {
            "appKey": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppKey"
            },
            "appToken": {
                "type": "apiKey",
                "in": "header",
                "name": "X-VTEX-API-AppToken"
            }
        }
    },
    "tags": [
        {
            "name": "Pricing Hub"
        }
    ],
    "security": [
        {
            "appKey": [],
            "appToken": []
        }
    ]
}