{
	"openapi": "3.0.0",
	"info": {
		"title": "Giftcard System API",
		"description": "This API is for management of Giftcards",
		"contact": {},
		"version": "1.0"
	},
	"servers": [
		{
			"url": "https://{accountName}.{environment}.com.br",
			"description": "VTEX server url",
			"variables": {
				"accountName": {
					"default": "apiexamples",
					"description": "Your VTEX account name"
				},
				"environment": {
					"enum": [
						"vtexcommercestable",
						"myvtex"
					],
					"default": "vtexcommercestable"
				}
			}
		}
	],
	"paths": {
		"/api/gift-card-system/pvt/giftCards": {
			"get": {
				"tags": [
					"Misc"
				],
				"summary": "List Giftcard",
				"description": "This API lists all the gift cards created by single customer.\r\n\r\nThis being said, it's really import to emphasize that the API does not lists all the store's gift cards.",
				"operationId": "ListGiftcard",
				"parameters": [
					{
						"name": "customerId",
						"in": "query",
						"description": "",
						"required": true,
						"style": "form",
						"explode": true,
						"schema": {
							"type": "string",
							"example": "{customerId}"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/json"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {
							"Cache-Control": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "no-cache"
									}
								}
							},
							"Connection": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "keep-alive"
									}
								}
							},
							"Content-Length": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "407"
									}
								}
							},
							"Date": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "Wed, 23 Nov 2016 19:54:07 GMT"
									}
								}
							},
							"Expires": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "-1"
									}
								}
							},
							"Pragma": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "no-cache"
									}
								}
							},
							"Server": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "nginx"
									}
								}
							},
							"X-CDNIgnore": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "1"
									}
								}
							},
							"X-Powered-by-VTEX-Janus-Edge": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "v1.29.18"
									}
								}
							},
							"X-Track": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "stable"
									}
								}
							},
							"X-VTEX-Janus-Router-Backend-App": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "gcsapi-v1.3.35"
									}
								}
							},
							"x-vtex-operation-id": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "33bfb015-6578-4f9a-a701-2f777d313ecf"
									}
								}
							}
						},
						"content": {
							"application/json; charset=utf-8": {
								"schema": {
									"$ref": "#/components/schemas/Sample"
								},
								"example": {
									"items": [
										{
											"id": 13,
											"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
											"balance": 1000,
											"cardName": "loyalty-program",
											"emissionDate": "2016-11-23T19:41:19.047",
											"expiringDate": "2017-11-23T17:50:34.76",
											"multipleCredits": true,
											"multipleRedemptions": true,
											"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
											"restrictedToOwner": false,
											"statusId": 1,
											"caption": "Fidelidade 2016"
										}
									],
									"paging": {
										"page": 1,
										"perPage": 10,
										"total": 1,
										"pages": 1
									}
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/api/gift-card-system/pvt/giftCards/": {
			"post": {
				"tags": [
					"Misc"
				],
				"summary": "Create Giftcard",
				"description": "",
				"operationId": "CreateGiftcard",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/json"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftcardRequest"
							},
							"example": {
								"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
								"cardName": "loyalty-program",
								"caption": "Fidelidade 2016",
								"expiringDate": "2017-04-01T00:00:00"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {
							"Cache-Control": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "no-cache"
									}
								}
							},
							"Connection": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "keep-alive"
									}
								}
							},
							"Content-Length": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "341"
									}
								}
							},
							"Date": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "Wed, 23 Nov 2016 19:41:09 GMT"
									}
								}
							},
							"Expires": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "-1"
									}
								}
							},
							"Pragma": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "no-cache"
									}
								}
							},
							"Server": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "nginx"
									}
								}
							},
							"X-CDNIgnore": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "1"
									}
								}
							},
							"X-Powered-by-VTEX-Janus-Edge": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "v1.29.18"
									}
								}
							},
							"X-Track": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "stable"
									}
								}
							},
							"X-VTEX-Janus-Router-Backend-App": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "gcsapi-v1.3.35"
									}
								}
							},
							"x-vtex-operation-id": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "664fc548-46b9-4f7c-bf7c-c590ae4c6329"
									}
								}
							}
						},
						"content": {
							"application/json; charset=utf-8": {
								"schema": {
									"$ref": "#/components/schemas/Sample1"
								},
								"example": {
									"id": 13,
									"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
									"balance": 0,
									"cardName": "loyalty-program",
									"emissionDate": "2016-11-23T19:41:19.0473712Z",
									"expiringDate": "2017-04-01T00:00:00",
									"multipleCredits": true,
									"multipleRedemptions": true,
									"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
									"restrictedToOwner": false,
									"statusId": 1,
									"caption": "Fidelidade 2016"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/api/gift-card-system/pvt/giftCards/{cardId}/credit": {
			"post": {
				"tags": [
					"Misc"
				],
				"summary": "Add / Remove Credit to Giftcard",
				"description": "",
				"operationId": "Add/RemoveCredittoGiftcard",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/json"
						}
					},
					{
						"name": "cardId",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Add~1RemoveCredittoGiftcardRequest"
							},
							"example": {
								"description": "Adiciona R$10,00",
								"value": 1000
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {
							"Cache-Control": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "no-cache"
									}
								}
							},
							"Connection": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "keep-alive"
									}
								}
							},
							"Content-Length": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "233"
									}
								}
							},
							"Date": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "Wed, 23 Nov 2016 19:50:37 GMT"
									}
								}
							},
							"Expires": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "-1"
									}
								}
							},
							"Pragma": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "no-cache"
									}
								}
							},
							"Server": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "nginx"
									}
								}
							},
							"X-CDNIgnore": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "1"
									}
								}
							},
							"X-Powered-by-VTEX-Janus-Edge": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "v1.29.18"
									}
								}
							},
							"X-Track": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "stable"
									}
								}
							},
							"X-VTEX-Janus-Router-Backend-App": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "gcsapi-v1.3.35"
									}
								}
							},
							"x-vtex-operation-id": {
								"content": {
									"text/plain": {
										"schema": {
											"type": "string"
										},
										"example": "2aaad43e-a4b0-4e61-8022-b64177d0d948"
									}
								}
							}
						},
						"content": {
							"application/json; charset=utf-8": {
								"schema": {
									"$ref": "#/components/schemas/Sample2"
								},
								"example": {
									"id": 13,
									"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
									"balance": 1000,
									"emissionDate": "2016-11-23T19:41:19.047",
									"expiringDate": "2017-11-23T17:50:34.76",
									"multipleCredits": true,
									"multipleRedemptions": true,
									"restrictedToOwner": false,
									"statusId": 1
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/api/gift-card-system/pvt/giftCards/{cardId}": {
			"patch": {
				"tags": [
					"Misc"
				],
				"summary": "Update Expiration Date",
				"description": "",
				"operationId": "UpdateExpirationDate",
				"parameters": [
					{
						"name": "Accept",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/json"
						}
					},
					{
						"name": "cardId",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/UpdateExpirationDateRequest"
							},
							"example": {
								"expiringDate": "AAAA-MM-DD"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {}
					}
				},
				"deprecated": false
			}
		}
	},
	"components": {
		"schemas": {
			"Sample": {
				"title": "Sample",
				"required": [
					"items",
					"paging"
				],
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item"
						},
						"description": ""
					},
					"paging": {
						"$ref": "#/components/schemas/Paging"
					}
				},
				"example": {
					"items": [
						{
							"id": 13,
							"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
							"balance": 1000,
							"cardName": "loyalty-program",
							"emissionDate": "2016-11-23T19:41:19.047",
							"expiringDate": "2017-11-23T17:50:34.76",
							"multipleCredits": true,
							"multipleRedemptions": true,
							"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
							"restrictedToOwner": false,
							"statusId": 1,
							"caption": "Fidelidade 2016"
						}
					],
					"paging": {
						"page": 1,
						"perPage": 10,
						"total": 1,
						"pages": 1
					}
				}
			},
			"Item": {
				"title": "Item",
				"required": [
					"id",
					"redemptionCode",
					"balance",
					"cardName",
					"emissionDate",
					"expiringDate",
					"multipleCredits",
					"multipleRedemptions",
					"customerId",
					"restrictedToOwner",
					"statusId",
					"caption"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"format": "int32"
					},
					"redemptionCode": {
						"type": "string"
					},
					"balance": {
						"type": "integer",
						"format": "int32"
					},
					"cardName": {
						"type": "string"
					},
					"emissionDate": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"multipleCredits": {
						"type": "boolean"
					},
					"multipleRedemptions": {
						"type": "boolean"
					},
					"customerId": {
						"type": "string"
					},
					"restrictedToOwner": {
						"type": "boolean"
					},
					"statusId": {
						"type": "integer",
						"format": "int32"
					},
					"caption": {
						"type": "string"
					}
				},
				"example": {
					"id": 13,
					"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
					"balance": 1000,
					"cardName": "loyalty-program",
					"emissionDate": "2016-11-23T19:41:19.047",
					"expiringDate": "2017-11-23T17:50:34.76",
					"multipleCredits": true,
					"multipleRedemptions": true,
					"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
					"restrictedToOwner": false,
					"statusId": 1,
					"caption": "Fidelidade 2016"
				}
			},
			"Paging": {
				"title": "Paging",
				"required": [
					"page",
					"perPage",
					"total",
					"pages"
				],
				"type": "object",
				"properties": {
					"page": {
						"type": "integer",
						"format": "int32"
					},
					"perPage": {
						"type": "integer",
						"format": "int32"
					},
					"total": {
						"type": "integer",
						"format": "int32"
					},
					"pages": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"page": 1,
					"perPage": 10,
					"total": 1,
					"pages": 1
				}
			},
			"CreateGiftcardRequest": {
				"title": "CreateGiftcardRequest",
				"required": [
					"customerId",
					"cardName",
					"caption",
					"expiringDate"
				],
				"type": "object",
				"properties": {
					"customerId": {
						"type": "string"
					},
					"cardName": {
						"type": "string"
					},
					"caption": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					}
				},
				"example": {
					"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
					"cardName": "loyalty-program",
					"caption": "Fidelidade 2016",
					"expiringDate": "2017-04-01T00:00:00"
				}
			},
			"Sample1": {
				"title": "Sample1",
				"required": [
					"id",
					"redemptionCode",
					"balance",
					"cardName",
					"emissionDate",
					"expiringDate",
					"multipleCredits",
					"multipleRedemptions",
					"customerId",
					"restrictedToOwner",
					"statusId",
					"caption"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"format": "int32"
					},
					"redemptionCode": {
						"type": "string"
					},
					"balance": {
						"type": "integer",
						"format": "int32"
					},
					"cardName": {
						"type": "string"
					},
					"emissionDate": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"multipleCredits": {
						"type": "boolean"
					},
					"multipleRedemptions": {
						"type": "boolean"
					},
					"customerId": {
						"type": "string"
					},
					"restrictedToOwner": {
						"type": "boolean"
					},
					"statusId": {
						"type": "integer",
						"format": "int32"
					},
					"caption": {
						"type": "string"
					}
				},
				"example": {
					"id": 13,
					"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
					"balance": 0,
					"cardName": "loyalty-program",
					"emissionDate": "2016-11-23T19:41:19.0473712Z",
					"expiringDate": "2017-04-01T00:00:00",
					"multipleCredits": true,
					"multipleRedemptions": true,
					"customerId": "3cc81d44-e42e-464b-8199-1e883bf4ab6a",
					"restrictedToOwner": false,
					"statusId": 1,
					"caption": "Fidelidade 2016"
				}
			},
			"Add/RemoveCredittoGiftcardRequest": {
				"title": "Add/RemoveCredittoGiftcardRequest",
				"required": [
					"description",
					"value"
				],
				"type": "object",
				"properties": {
					"description": {
						"type": "string"
					},
					"value": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"description": "Adiciona R$10,00",
					"value": 1000
				}
			},
			"Sample2": {
				"title": "Sample2",
				"required": [
					"id",
					"redemptionCode",
					"balance",
					"emissionDate",
					"expiringDate",
					"multipleCredits",
					"multipleRedemptions",
					"restrictedToOwner",
					"statusId"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "integer",
						"format": "int32"
					},
					"redemptionCode": {
						"type": "string"
					},
					"balance": {
						"type": "integer",
						"format": "int32"
					},
					"emissionDate": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"multipleCredits": {
						"type": "boolean"
					},
					"multipleRedemptions": {
						"type": "boolean"
					},
					"restrictedToOwner": {
						"type": "boolean"
					},
					"statusId": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"id": 13,
					"redemptionCode": "BWNW-PQEH-FFRB-ESNL",
					"balance": 1000,
					"emissionDate": "2016-11-23T19:41:19.047",
					"expiringDate": "2017-11-23T17:50:34.76",
					"multipleCredits": true,
					"multipleRedemptions": true,
					"restrictedToOwner": false,
					"statusId": 1
				}
			},
			"UpdateExpirationDateRequest": {
				"title": "UpdateExpirationDateRequest",
				"required": [
					"expiringDate"
				],
				"type": "object",
				"properties": {
					"expiringDate": {
						"type": "string",
						"default": "2030-01-10"
					}
				},
				"example": {
					"expiringDate": "AAAA-MM-DD"
				}
			}
		},
		"securitySchemes": {
			"appKey": {
				"type": "apiKey",
				"in": "header",
				"name": "X-VTEX-API-AppKey"
			},
			"appToken": {
				"type": "apiKey",
				"in": "header",
				"name": "X-VTEX-API-AppToken"
			}
		}
	},
	"tags": [
		{
			"name": "Misc",
			"description": ""
		}
	],
	"security": [
		{
			"appKey": [],
			"appToken": []
		}
	]
}