{
    "openapi": "3.0.0",
    "info": {
        "title": "Buyer Organizations API",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://buyer-organizations.vtex.com/buyer-orgs",
            "description": "VTEX server URL"
        }
    ],
    "paths": {
        "/buyer-orgs": {
            "post": {
                "tags": [
                    "Buyer Organizations"
                ],
                "summary": "Create Buyer Organization",
                "description": "Creates a Buyer Organization",
                "operationId": "CreateBuyerOrg",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateBuyerOrgRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "title": "",
                                    "example": {
                                        "token": "d0d98932-f982-475b-b491-8255aa8029d8"
                                    },
                                    "properties": {
                                        "token": {
                                            "type": "string",
                                            "description": "Token of the Buyer Organization creation job"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/buyer-orgs/{job-token}": {
            "get": {
                "tags": [
                    "Buyer Organizations"
                ],
                "summary": "Retrieve Buyer Organization creation status",
                "description": "Retrieves the creation job status of a Buyer Organization",
                "operationId": "BuyerOrgsCreationJobStatus",
                "parameters": [
                    {
                        "name": "job-token",
                        "in": "path",
                        "description": "Token of the Buyer Organization creation job",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "e7d74c3b-94b8-447e-8b2c-cc33e892e765"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "id": "d0d98932-f982-475b-b491-8255aa8029d8",
                                    "status": "DONE",
                                    "createdAt": "2021-10-06T19:51:56.135321+00:00",
                                    "updatedAt": "2021-10-06T19:52:01.564753+00:00"
                                },
                                "schema": {
                                    "type": "object",
                                    "title": "",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "description": "Token of the Buyer Organization creation job"
                                        },
                                        "status": {
                                            "type": "string",
                                            "description": "Status of the Buyer Organization creation job"
                                        },
                                        "createdAt": {
                                            "type": "string",
                                            "description": "Date and time when the Buyer Organization job was created"
                                        },
                                        "updatedAt": {
                                            "type": "string",
                                            "description": "Date and time when the Buyer Organization job was last updated"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/by-user-email": {
            "get": {
                "tags": [
                    "Buyer Organizations"
                ],
                "summary": "Retrieve Buyer Organizations by User Email",
                "description": "Retrieves Buyer Organizations associated with a given user email",
                "operationId": "BObyUserEmail",
                "parameters": [
                    {
                        "name": "email",
                        "in": "query",
                        "description": "User email",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "default": "john@mail.com"
                        }
                    },
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "id": "0cfc5385-1bc7-44ab-99e8-66553f77abdd",
                                    "tenantName": "cmpny15170336",
                                    "createdAt": "2021-10-06T20:07:27.204424+00:00",
                                    "updatedAt": "2021-10-06T20:07:27.204424+00:00",
                                    "organizationEmail": "company@email.com",
                                    "address": {
                                        "id": "11c7e284-d86a-4e0a-b316-84e4f9d00c0f",
                                        "country": "BRA",
                                        "zipCode": "22250040",
                                        "state": "RJ",
                                        "city": "Rio de Janeiro",
                                        "neighborhood": "Botafogo",
                                        "street": "Praia de Botafogo",
                                        "streetNumber": "300",
                                        "complement": "Block 1",
                                        "roomFloorUnit": "3rd floor",
                                        "createdAt": "2021-10-06T20:07:27.204424+00:00",
                                        "updatedAt": "2021-10-06T20:07:27.204424+00:00"
                                    },
                                    "company": {
                                        "id": "efd2c530-8bfc-45a6-babe-52cb243d3118",
                                        "corporateDocument": "15.170.336/0001-70",
                                        "companyName": "Company",
                                        "tradeName": "Company",
                                        "stateRegistration": "",
                                        "createdAt": "2021-10-06T20:07:27.204424+00:00",
                                        "updatedAt": "2021-10-06T20:07:27.204424+00:00"
                                    }
                                },
                                "schema": {
                                    "type": "object",
                                    "title": "",
                                    "properties": {
                                        "id": {
                                            "type": "string",
                                            "description": "Buyer Organization unique identification code"
                                        },
                                        "tenantName": {
                                            "type": "string",
                                            "description": "Buyer Organization tenant name"
                                        },
                                        "createdAt": {
                                            "type": "string",
                                            "description": "Date and time when the Buyer Organization was created"
                                        },
                                        "updatedAt": {
                                            "type": "string",
                                            "description": "Date and time when the Buyer Organization was last updated"
                                        },
                                        "organizationEmail": {
                                            "type": "string",
                                            "description": ""
                                        },
                                        "address": {
                                            "type": "object",
                                            "properties": {
                                                "country": {
                                                    "type": "string",
                                                    "description": "Country where the organization is based"
                                                },
                                                "zipCode": {
                                                    "type": "string",
                                                    "description": "ZIP Code or postal code of the organization's address"
                                                },
                                                "complement": {
                                                    "type": "string",
                                                    "description": "Complementary information to the organization's address"
                                                },
                                                "street": {
                                                    "type": "string",
                                                    "description": "Street address of the organization"
                                                },
                                                "streetNumber": {
                                                    "type": "string",
                                                    "description": "Street number of the organization’s billing and shipping address"
                                                },
                                                "neighborhood": {
                                                    "type": "string",
                                                    "description": "Neighborhood where the organization is located"
                                                },
                                                "state": {
                                                    "type": "string",
                                                    "description": "State where the organization is located"
                                                },
                                                "city": {
                                                    "type": "string",
                                                    "description": "City where the organization is located"
                                                },
                                                "createdAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the Buyer Organization address information was created"
                                                },
                                                "updatedAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the Buyer Organization address was last updated"
                                                }
                                            }
                                        },
                                        "company": {
                                            "type": "object",
                                            "properties": {
                                                "corporateDocument": {
                                                    "type": "string",
                                                    "description": "The organization’s tax identification number"
                                                },
                                                "companyName": {
                                                    "type": "string",
                                                    "description": "Legal corporate name registered by the organization"
                                                },
                                                "tradeName": {
                                                    "type": "string",
                                                    "description": "The organization's trade name"
                                                },
                                                "stateRegistration": {
                                                    "type": "string",
                                                    "description": "State registration number of the organization"
                                                },
                                                "createdAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the Buyer Organization company information was created"
                                                },
                                                "updatedAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the Buyer Organization company information was last updated"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/buyer-orgs/generate-tenant-name": {
            "post": {
                "tags": [
                    "Buyer Organizations"
                ],
                "summary": "Generate Buyer Organization Tenant Name",
                "description": "Generates a tenant name for a Buyer Organization",
                "operationId": "GenerateTenantName",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/GenerateTenantNameRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "text/plain": {
                                "example": "cmpny15170336",
                                "schema": {
                                    "type": "string",
                                    "description": "Buyer Organization tenant name"
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/users/{tenant}": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Create New Buyer Organization User",
                "description": "Creates a new Buyer Organization User",
                "operationId": "NewUser",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "tenant",
                        "in": "path",
                        "description": "Buyer Organization tenant name",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "cmpny15170336"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/NewUserRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "content": {
                                        "id": "98dee8ff-b033-4ec5-8a17-e2f44ba9f346",
                                        "name": "Louise Smith",
                                        "email": "louise@email.com",
                                        "phone": "5521999999999",
                                        "tenant": "cmpny15170336",
                                        "createdAt": "2021-10-06T20:59:36.142281+00:00",
                                        "updatedAt": "2021-10-06T20:59:36.142281+00:00"
                                    },
                                    "status": "SUCCESS"
                                },
                                "schema": {
                                    "type": "object",
                                    "title": "",
                                    "properties": {
                                        "content": {
                                            "type": "object",
                                            "description": "User information",
                                            "properties": {
                                                "id": {
                                                    "type": "string",
                                                    "description": "User unique identification code"
                                                },
                                                "name": {
                                                    "type": "string",
                                                    "description": "Full name of the Buyer Organization user"
                                                },
                                                "email": {
                                                    "type": "string",
                                                    "description": "The user's work email address"
                                                },
                                                "phone": {
                                                    "type": "string",
                                                    "description": "The user's work phone number"
                                                },
                                                "tenant": {
                                                    "type": "string",
                                                    "description": "Buyer Organization tenant name"
                                                },
                                                "createdAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the user was created"
                                                },
                                                "updatedAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the user was last updated"
                                                }
                                            }
                                        },
                                        "status": {
                                            "type": "string",
                                            "description": "Status of the user creation job"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "text/plain": {
                                "example": "ALREADY_EXISTS",
                                "schema": {
                                    "type": "string",
                                    "description": "If the response is `ALREADY_EXISTS`, there already exists a user that is registered with the provided `email` and associated with the Buyer Organization. \n\n If the response is `NOT_FOUND`, the `tenant` does not exist."
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "List Buyer Organization Users",
                "description": "Retrieves information from all users associated with a specific Buyer Organization",
                "operationId": "Users",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "tenant",
                        "in": "path",
                        "description": "Buyer Organization tenant name",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "cmpny15170336"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "content": [
                                        {
                                            "id": "109e812a-8589-4f55-bd7b-7771eced2038",
                                            "name": "John Doe",
                                            "email": "john@mail.com",
                                            "phone": "123456",
                                            "tenant": "cmpny15170336",
                                            "createdAt": "2021-10-06T20:07:27.59029+00:00",
                                            "updatedAt": "2021-10-06T20:07:27.59029+00:00"
                                        },
                                        {
                                            "id": "98dee8ff-b033-4ec5-8a17-e2f44ba9f346",
                                            "name": "Jane Doe",
                                            "email": "jane@mail.com",
                                            "phone": "9999999999",
                                            "tenant": "cmpny15170336",
                                            "createdAt": "2021-10-06T20:59:36.142281+00:00",
                                            "updatedAt": "2021-10-06T20:59:36.142281+00:00"
                                        }
                                    ],
                                    "status": "SUCCESS"
                                },
                                "schema": {
                                    "type": "object",
                                    "title": "",
                                    "properties": {
                                        "content": {
                                            "type": "array",
                                            "description": "List of Buyer Organization Users",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string",
                                                        "description": "User unique identification code"
                                                    },
                                                    "name": {
                                                        "type": "string",
                                                        "description": "Full name of the Buyer Organization user"
                                                    },
                                                    "email": {
                                                        "type": "string",
                                                        "description": "The user's work email address"
                                                    },
                                                    "phone": {
                                                        "type": "string",
                                                        "description": "The user's work phone number"
                                                    },
                                                    "tenant": {
                                                        "type": "string",
                                                        "description": "Buyer Organization tenant name"
                                                    },
                                                    "createdAt": {
                                                        "type": "string",
                                                        "description": "Date and time when the user was created"
                                                    },
                                                    "updatedAt": {
                                                        "type": "string",
                                                        "description": "Date and time when the user was last updated"
                                                    }
                                                }
                                            }
                                        },
                                        "status": {
                                            "type": "string",
                                            "description": "Status of the request"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "text/plain": {
                                "example": "NOT_FOUND",
                                "schema": {
                                    "type": "string",
                                    "description": "If the response is `NOT_FOUND`, the `tenant` does not exist"
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/users/{tenant}/{userId}": {
            "put": {
                "tags": [
                    "Users"
                ],
                "summary": "Update Buyer Organization User information",
                "description": "Update information of a specific Buyer Organization User",
                "operationId": "User",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "tenant",
                        "in": "path",
                        "description": "Buyer Organization tenant name",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "cmpny15542400"
                        }
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "description": "User unique identification code",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "3d5717b6-9a04-49f6-acf6-73b27b33bd06"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserRequest"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "content": {
                                        "id": "98dee8ff-b033-4ec5-8a17-e2f44ba9f346",
                                        "name": "Maria Taylor",
                                        "email": "maria@mail.com",
                                        "phone": "9999999999",
                                        "tenant": "cmpny15170336",
                                        "createdAt": "0001-01-01T00:00:00",
                                        "updatedAt": "0001-01-01T00:00:00"
                                    },
                                    "status": "SUCCESS"
                                },
                                "schema": {
                                    "type": "object",
                                    "title": "",
                                    "properties": {
                                        "content": {
                                            "type": "object",
                                            "description": "User information",
                                            "properties": {
                                                "id": {
                                                    "type": "string",
                                                    "description": "User unique identification code"
                                                },
                                                "name": {
                                                    "type": "string",
                                                    "description": "Full name of the Buyer Organization user"
                                                },
                                                "email": {
                                                    "type": "string",
                                                    "description": "The user's work email address"
                                                },
                                                "phone": {
                                                    "type": "string",
                                                    "description": "The user's work phone number"
                                                },
                                                "tenant": {
                                                    "type": "string",
                                                    "description": "Buyer Organization tenant name"
                                                },
                                                "createdAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the user was created"
                                                },
                                                "updatedAt": {
                                                    "type": "string",
                                                    "description": "Date and time when the user was last updated"
                                                }
                                            }
                                        },
                                        "status": {
                                            "type": "string",
                                            "description": "Status of the update request"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "text/plain": {
                                "example": "NOT_FOUND",
                                "schema": {
                                    "type": "string",
                                    "description": "If the response is `NOT_FOUND`, the `tenant` does not exist"
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "Users"
                ],
                "summary": "Delete Buyer Organization User",
                "description": "Deletes a specific Buyer Organization User",
                "operationId": "User1",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "tenant",
                        "in": "path",
                        "description": "Buyer Organization tenant name",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "cmpny15170336"
                        }
                    },
                    {
                        "name": "userId",
                        "in": "path",
                        "description": "User unique identification code",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "98dee8ff-b033-4ec5-8a17-e2f44ba9f346"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "text/plain": {
                                "example": "NOT_FOUND",
                                "schema": {
                                    "type": "string",
                                    "description": "If the response is `NOT_FOUND`, the `tenant` does not exist"
                                }
                            }
                        }
                    }
                },
                "deprecated": false
            }
        },
        "/meta/healthcheck": {
            "get": {
                "tags": [
                    "Health Check"
                ],
                "summary": "Health Check",
                "description": "Retrieves the health check status. The `200 OK` response means your requests to the **Buyer Organizations API** are being successfully submitted. If your request results in a timeout, this means the system is unstable or offline.",
                "operationId": "HealthCheck",
                "parameters": [
                    {
                        "name": "Accept",
                        "in": "header",
                        "description": "HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand ",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    },
                    {
                        "name": "Content-Type",
                        "in": "header",
                        "description": "Describes the type of the content being sent",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "default": "application/json"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                },
                "deprecated": false
            }
        }
    },
    "components": {
        "schemas": {
            "CreateBuyerOrgRequest": {
                "title": "",
                "required": [
                    "address",
                    "company",
                    "tenantName",
                    "organizationEmail",
                    "firstUser"
                ],
                "type": "object",
                "properties": {
                    "address": {
                        "$ref": "#/components/schemas/Address"
                    },
                    "company": {
                        "$ref": "#/components/schemas/Company"
                    },
                    "tenantName": {
                        "type": "string"
                    },
                    "organizationEmail": {
                        "type": "string"
                    },
                    "firstUser": {
                        "$ref": "#/components/schemas/FirstUser"
                    }
                },
                "default": {
                    "address": {
                        "country": "BRA",
                        "zipCode": "22250040",
                        "complement": "3rd floor",
                        "street": "Praia de Botafogo",
                        "streetNumber": "300",
                        "neighborhood": "Botafogo",
                        "state": "RJ",
                        "city": "Rio de Janeiro"
                    },
                    "company": {
                        "corporateDocument": "15.170.336/0001-70",
                        "companyName": "company",
                        "tradeName": "company",
                        "stateRegistration": "123456"
                    },
                    "tenantName": "cmpny15170336",
                    "organizationEmail": "company@email.com",
                    "firstUser": {
                        "name": "Jane Doe",
                        "email": "janedoe@email.com",
                        "phone": "123456",
                        "password": "vtex123"
                    }
                }
            },
            "Address": {
                "title": "",
                "required": [
                    "country",
                    "zipCode",
                    "complement",
                    "street",
                    "streetNumber",
                    "neighborhood",
                    "state",
                    "city"
                ],
                "type": "object",
                "properties": {
                    "country": {
                        "type": "string",
                        "description": "Country where the organization is based"
                    },
                    "zipCode": {
                        "type": "string",
                        "description": "ZIP Code or postal code of the organization's address"
                    },
                    "complement": {
                        "type": "string",
                        "description": "Complementary information to the organization's address"
                    },
                    "street": {
                        "type": "string",
                        "description": "Street address of the organization"
                    },
                    "streetNumber": {
                        "type": "string",
                        "description": "Street number of the organization’s billing and shipping address"
                    },
                    "neighborhood": {
                        "type": "string",
                        "description": "Neighborhood where the organization is located"
                    },
                    "state": {
                        "type": "string",
                        "description": "State where the organization is located"
                    },
                    "city": {
                        "type": "string",
                        "description": "City where the organization is located"
                    }
                },
                "default": {
                    "country": "BRA",
                    "zipCode": "22250040",
                    "complement": "3rd floor",
                    "street": "Praia de Botafogo",
                    "streetNumber": "300",
                    "neighborhood": "Botafogo",
                    "state": "RJ",
                    "city": "Rio de Janeiro"
                }
            },
            "Company": {
                "title": "",
                "required": [
                    "corporateDocument",
                    "companyName",
                    "tradeName",
                    "stateRegistration"
                ],
                "type": "object",
                "properties": {
                    "corporateDocument": {
                        "type": "string",
                        "description": "The organization's tax identification number. Must be consistent with the organization's country. E.g.: the value should be a valid EIN if the organization is based in the USA, or a valid CNPJ if it is based in Brazil"
                    },
                    "companyName": {
                        "type": "string",
                        "description": "Legal corporate name registered by the organization"
                    },
                    "tradeName": {
                        "type": "string",
                        "description": "The organization's trade name"
                    },
                    "stateRegistration": {
                        "type": "string",
                        "description": "State registration number of the organization"
                    }
                },
                "default": {
                    "corporateDocument": "15.170.336/0001-70",
                    "companyName": "company",
                    "tradeName": "company",
                    "stateRegistration": "123456"
                }
            },
            "FirstUser": {
                "title": "",
                "required": [
                    "name",
                    "email",
                    "phone",
                    "password"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Full name of the Buyer Organization user"
                    },
                    "email": {
                        "type": "string",
                        "description": "The user's work email address"
                    },
                    "phone": {
                        "type": "string",
                        "description": "The user's work phone number"
                    },
                    "password": {
                        "type": "string",
                        "description": "The user's individual password. It should have at least 8 characters, including 1 uppercase letter, 1 lowercase letter and 1 number"
                    }
                },
                "default": {
                    "name": "John Doe",
                    "email": "john@email.com",
                    "phone": "999999999",
                    "password": "Password123"
                }
            },
            "GenerateTenantNameRequest": {
                "title": "",
                "required": [
                    "company",
                    "address"
                ],
                "type": "object",
                "properties": {
                    "company": {
                        "$ref": "#/components/schemas/Company1"
                    },
                    "address": {
                        "$ref": "#/components/schemas/Address1"
                    }
                },
                "default": {
                    "company": {
                        "corporateDocument": "15.170.336/0001-70",
                        "companyName": "company",
                        "tradeName": "company"
                    },
                    "address": {
                        "country": "BRA"
                    }
                }
            },
            "Company1": {
                "title": "",
                "required": [
                    "corporateDocument",
                    "companyName",
                    "tradeName"
                ],
                "type": "object",
                "properties": {
                    "corporateDocument": {
                        "type": "string",
                        "description": "The organization's tax identification number. Must be consistent with the organization's country. E.g.: the value should be a valid EIN if the organization is based in the USA, or a valid CNPJ if it is based in Brazil"
                    },
                    "companyName": {
                        "type": "string",
                        "description": "Legal corporate name registered by the organization"
                    },
                    "tradeName": {
                        "type": "string",
                        "description": "The organization's trade name"
                    }
                },
                "default": {
                    "corporateDocument": "15.170.336/0001-70",
                    "companyName": "Company",
                    "tradeName": "Company"
                }
            },
            "Address1": {
                "title": "",
                "required": [
                    "country"
                ],
                "type": "object",
                "properties": {
                    "country": {
                        "type": "string",
                        "description": "Country where the organization is based"
                    }
                },
                "default": {
                    "country": "BRA"
                }
            },
            "NewUserRequest": {
                "title": "",
                "required": [
                    "email",
                    "name",
                    "phone",
                    "password"
                ],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "description": "The user's work email address"
                    },
                    "name": {
                        "type": "string",
                        "description": "Full name of the Buyer Organization user"
                    },
                    "phone": {
                        "type": "string",
                        "description": "The user's work phone number"
                    },
                    "password": {
                        "type": "string",
                        "description": "The user's individual password. It should have at least 8 characters, including 1 uppercase letter, 1 lowercase letter and 1 number"
                    }
                },
                "default": {
                    "email": "john@email.com",
                    "name": "John Doe",
                    "phone": "999999999",
                    "password": "Password123"
                }
            },
            "UserRequest": {
                "title": "",
                "required": [
                    "email",
                    "name",
                    "phone",
                    "password"
                ],
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "description": "The user's work email address"
                    },
                    "name": {
                        "type": "string",
                        "description": "Full name of the Buyer Organization user"
                    },
                    "phone": {
                        "type": "string",
                        "description": "The user's work phone number"
                    },
                    "password": {
                        "type": "string",
                        "description": "The user's individual password. It should have at least 8 characters, including 1 uppercase letter, 1 lowercase letter and 1 number"
                    }
                },
                "default": {
                    "email": "maria@mail.com",
                    "name": "Maria Taylor",
                    "phone": "9999999999",
                    "password": "Password123"
                }
            }
        }
    },
    "security": [],
    "tags": [
        {
            "name": "Buyer Organizations"
        },
        {
            "name": "Users"
        },
        {
            "name": "Health Check"
        }
    ]
}