{
	"openapi": "3.0.0",
	"info": {
		"title": "GiftCard API",
		"description": "",
		"contact": {},
		"version": "1.0"
	},
	"servers": [
		{
			"url": "https://{accountName}.{environment}.com.br",
			"description": "VTEX server url"
		}
	],
	"paths": {
		"/giftcards": {
			"post": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Create GiftCard",
				"description": "",
				"operationId": "CreateGiftCard",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcard.v1+json"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/vnd.vtex.giftcard.v1+json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftCardRequest"
							},
							"example": {
								"relationName": "loyalty-program",
								"expiringDate": "2016-01-01T00:00:00",
								"caption": "Programa Vtex Fidelidade",
								"redemptionCode": "BAHD-ASDB-ADQW-ASDQ"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response"
								},
								"example": {
									"id": "954",
									"redemptionToken": "32ScL57220Vapb8pc50HJ3mWH1cl1L8x",
									"redemptionCode": "***********ASDQ",
									"balance": 0,
									"relationName": "cardName",
									"emissionDate": "2014-04-24T20:22:58.163",
									"expiringDate": "2016-01-01T00:00:00",
									"caption": "Programa Vtex Fidelidade",
									"transactions": {
										"href": "cards/954/transactions"
									}
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}": {
			"get": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get GiftCard by ID",
				"description": "Return a especific giftcard",
				"operationId": "GetGiftCardbyID",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response"
								},
								"example": {
									"id": "954",
									"redemptionToken": "32ScL57220Vapb8pc50HJ3mWH1cl1L8x",
									"redemptionCode": "***********ASDQ",
									"balance": 0,
									"relationName": "cardName",
									"emissionDate": "2014-04-24T20:22:58.163",
									"expiringDate": "2016-01-01T00:00:00",
									"caption": "Programa Vtex Fidelidade",
									"transactions": {
										"href": "cards/954/transactions"
									}
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/_search": {
			"post": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get GiftCard using JSON",
				"description": "",
				"operationId": "GetGiftCardusingJSON",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "REST-Range",
						"in": "header",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "giftcard=0-49"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/GetGiftCardusingJSONRequest"
							},
							"example": {
								"cart": {
									"grandTotal": 123.1,
									"relationName": null,
									"redemptionCode": null,
									"discounts": 0,
									"shipping": 0,
									"taxes": 12,
									"items": [
										{
											"productId": "1",
											"id": "1",
											"refId": "12",
											"name": "Product Name",
											"price": 100,
											"quantity": 1
										}
									],
									"itemsTotal": 100
								},
								"client": {
									"id": "019a0cc1-409a-4c16-859b-eefdb81f825e",
									"email": "email@damoain.com",
									"document": "21301923110"
								}
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response2"
								},
								"example": {
									"items": [
										{
											"id": "589",
											"_self": {
												"href": "cards/589"
											}
										},
										{
											"id": "590",
											"_self": {
												"href": "cards/590"
											}
										},
										{
											"id": "591",
											"_self": {
												"href": "cards/591"
											}
										},
										{
											"id": "592",
											"_self": {
												"href": "cards/592"
											}
										}
									],
									"paging": {
										"page": 0,
										"perPage": 10,
										"total": 4,
										"pages": 1
									}
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions": {
			"get": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get GiftCard Transactions",
				"description": "Returns all transaction of a giftcard",
				"operationId": "GetGiftCardTransactions",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/response3"
									}
								},
								"example": [
									{
										"id": "268",
										"_self": {
											"href": "cards/890/transactions/268"
										}
									},
									{
										"id": "269",
										"_self": {
											"href": "cards/890/transactions/269"
										}
									},
									{
										"id": "270",
										"_self": {
											"href": "cards/890/transactions/270"
										}
									}
								]
							}
						}
					}
				},
				"deprecated": false
			},
			"post": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Create GiftCard Transaction",
				"description": "",
				"operationId": "CreateGiftCardTransaction",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/CreateGiftCardTransactionRequest"
							},
							"example": {
								"operation": "Debit",
								"value": 3,
								"description": "GiftCardHub",
								"redemptionToken": "b2dac6f2-f365-48cd-82a9-0b376a55557a",
								"redemptionCode": "",
								"requestId": "B56CBE231DEE4E1A859183C1030CE926",
								"orderInfo": {
									"orderId": "v5006128str",
									"sequence": 5006128,
									"cart": {
										"items": [
											{
												"id": "2001023",
												"productId": "2000492",
												"refId": "35994",
												"name": "Vaporizador Des. Colônia Branco",
												"value": 14.99,
												"price": 14.99,
												"quantity": 1,
												"shippingDiscount": 0,
												"discount": -7.5,
												"priceTags": [
													{
														"name": "discount@price-discount_store_183#4911bf6f-22a2-4af1-a365-cce895c3df2c",
														"value": 0
													}
												]
											}
										],
										"grandTotal": 0,
										"discounts": -7.5,
										"shipping": 7.27,
										"taxes": 0,
										"itemsTotal": 14.99
									},
									"clientProfile": {
										"email": "miguel.scott96@yahoo.com.br",
										"firstName": "miguel",
										"lastName": "scott",
										"document": "02906792063",
										"phone": "+551111111111",
										"birthDate": "0001-01-01T00:00:00",
										"isCorporate": false
									},
									"shipping": {
										"receiverName": "miguel scott",
										"postalCode": "22250040",
										"city": "Rio de Janeiro",
										"state": "RJ",
										"country": "BRA",
										"street": "Praia de Botafogo",
										"number": "111",
										"neighborhood": "Botafogo",
										"complement": null,
										"reference": null
									}
								}
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response3"
								},
								"example": {
									"id": "2541",
									"_self": {
										"href": "providers/VtexGiftCardProvider/cards/890/transactions/2451"
									}
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}": {
			"get": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get GiftCard Transaction by ID",
				"description": "",
				"operationId": "GetGiftCardTransactionbyID",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response5"
								},
								"example": {
									"value": 123.4,
									"description": "Crédito relacionado a compra 10281230-01",
									"date": "2016-01-01T00:00:00",
									"redemptionMode": "redemptionToken"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}/authorization": {
			"get": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get Transaction Authorizations",
				"description": "Returns the giftcard transaction authorizations",
				"operationId": "GetTransactionAuthorizations",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response6"
								},
								"example": {
									"oid": "7cf8d7970e1c81d05620e46cceb6819f",
									"value": 123.4,
									"date": "2016-01-01T00:00:00"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}/cancellations": {
			"get": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get Transaction Cancellations",
				"description": "Returns the giftcard transaction cancellations",
				"operationId": "GetTransactionCancellations",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/response7"
									}
								},
								"example": [
									{
										"id": "239d35b430fc75379db966c1d3670c6f",
										"value": 13.4,
										"date": "2016-04-06T00:00:00"
									},
									{
										"id": "49f0bad299687c62334182178bfd75d8",
										"value": 10.4,
										"date": "2016-05-06T00:00:00"
									}
								]
							}
						}
					}
				},
				"deprecated": false
			},
			"post": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Cancel GiftCard Transaction",
				"description": "",
				"operationId": "CancelGiftCardTransaction",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/CancelGiftCardTransactionRequest"
							},
							"example": {
								"value": 13,
								"requestId": "6360f98eb0cf6fd5afa77e39bba8c20fe5807d8c"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response6"
								},
								"example": {
									"oid": "239d35b430fc75379db966c1d3670c6f",
									"value": 13.4,
									"date": "2016-04-06T00:00:00"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		},
		"/giftcards/{giftCardID}/transactions/{transactionID}/settlements": {
			"get": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Get Transaction Settlements",
				"description": "Returns the giftcard transaction settlements",
				"operationId": "GetTransactionSettlements",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/response6"
									}
								},
								"example": [
									{
										"oid": "b8e0c606b2fe543e5b0e639575cd9723",
										"value": 17.4,
										"date": "2016-04-06T00:00:00"
									},
									{
										"oid": "6cb6cd63c16e219b1eee61f2",
										"value": 10.4,
										"date": "2016-05-06T00:00:00"
									}
								]
							}
						}
					}
				},
				"deprecated": false
			},
			"post": {
				"tags": [
					"Miscellaneous"
				],
				"summary": "Settle GiftCard Transaction",
				"description": "Creates a giftcard transaction settlement",
				"operationId": "SettleGiftCardTransaction",
				"parameters": [
					{
						"name": "accountName",
						"in": "path",
						"required": true,
						"description": "Name of the VTEX account. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "apiexamples"
						}
					},
					{
						"name": "environment",
						"in": "path",
						"required": true,
						"description": "Environment to use. Used as part of the URL",
						"schema": {
							"type": "string",
							"default": "vtexcommercestable"
						}
					},
					{
						"name": "Accept",
						"in": "header",
						"description": "Media type(s) that is/are acceptable for the response. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "Content-Type",
						"in": "header",
						"description": "The Media type of the body of the request. Default value for payment provider protocol is application/json",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string",
							"example": "application/vnd.vtex.giftcardproviders.v1+json"
						}
					},
					{
						"name": "giftCardID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "transactionID",
						"in": "path",
						"description": "",
						"required": true,
						"style": "simple",
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"description": "",
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/SettleGiftCardTransactionRequest"
							},
							"example": {
								"value": 17.4,
								"requestId": "6360f98eb0cf6fd5afa77e39bba8c20fe5807d8c"
							}
						}
					},
					"required": true
				},
				"responses": {
					"200": {
						"description": "",
						"headers": {},
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/response6"
								},
								"example": {
									"oid": "b8e0c606b2fe543e5b0e639575cd9723",
									"value": 17.4,
									"date": "2016-04-06T00:00:00"
								}
							}
						}
					}
				},
				"deprecated": false
			}
		}
	},
	"components": {
		"schemas": {
			"CreateGiftCardRequest": {
				"title": "CreateGiftCardRequest",
				"required": [
					"relationName",
					"expiringDate",
					"caption",
					"redemptionCode"
				],
				"type": "object",
				"properties": {
					"relationName": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"caption": {
						"type": "string"
					},
					"redemptionCode": {
						"type": "string"
					}
				},
				"example": {
					"relationName": "loyalty-program",
					"expiringDate": "2016-01-01T00:00:00",
					"caption": "Programa Vtex Fidelidade",
					"redemptionCode": "BAHD-ASDB-ADQW-ASDQ"
				}
			},
			"response": {
				"title": "response",
				"required": [
					"id",
					"redemptionToken",
					"redemptionCode",
					"balance",
					"relationName",
					"emissionDate",
					"expiringDate",
					"caption",
					"transactions"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"redemptionToken": {
						"type": "string"
					},
					"redemptionCode": {
						"type": "string"
					},
					"balance": {
						"type": "integer",
						"format": "int32"
					},
					"relationName": {
						"type": "string"
					},
					"emissionDate": {
						"type": "string"
					},
					"expiringDate": {
						"type": "string"
					},
					"caption": {
						"type": "string"
					},
					"transactions": {
						"$ref": "#/components/schemas/Transactions"
					}
				},
				"example": {
					"id": "954",
					"redemptionToken": "32ScL57220Vapb8pc50HJ3mWH1cl1L8x",
					"redemptionCode": "***********ASDQ",
					"balance": 0,
					"relationName": "cardName",
					"emissionDate": "2014-04-24T20:22:58.163",
					"expiringDate": "2016-01-01T00:00:00",
					"caption": "Programa Vtex Fidelidade",
					"transactions": {
						"href": "cards/954/transactions"
					}
				}
			},
			"Transactions": {
				"title": "Transactions",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "cards/954/transactions"
				}
			},
			"GetGiftCardusingJSONRequest": {
				"title": "GetGiftCardusingJSONRequest",
				"required": [
					"cart",
					"client"
				],
				"type": "object",
				"properties": {
					"cart": {
						"$ref": "#/components/schemas/Cart"
					},
					"client": {
						"$ref": "#/components/schemas/Client"
					}
				},
				"example": {
					"cart": {
						"grandTotal": 123.1,
						"relationName": null,
						"redemptionCode": null,
						"discounts": 0,
						"shipping": 0,
						"taxes": 12,
						"items": [
							{
								"productId": "1",
								"id": "1",
								"refId": "12",
								"name": "Product Name",
								"price": 100,
								"quantity": 1
							}
						],
						"itemsTotal": 100
					},
					"client": {
						"id": "019a0cc1-409a-4c16-859b-eefdb81f825e",
						"email": "email@damoain.com",
						"document": "21301923110"
					}
				}
			},
			"Cart": {
				"title": "Cart",
				"required": [
					"grandTotal",
					"relationName",
					"redemptionCode",
					"discounts",
					"shipping",
					"taxes",
					"items",
					"itemsTotal"
				],
				"type": "object",
				"properties": {
					"grandTotal": {
						"type": "number"
					},
					"relationName": {
						"type": "string",
						"nullable": true
					},
					"redemptionCode": {
						"type": "string",
						"nullable": true
					},
					"discounts": {
						"type": "integer",
						"format": "int32"
					},
					"shipping": {
						"type": "integer",
						"format": "int32"
					},
					"taxes": {
						"type": "integer",
						"format": "int32"
					},
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item"
						},
						"description": ""
					},
					"itemsTotal": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"grandTotal": 123.1,
					"relationName": null,
					"redemptionCode": null,
					"discounts": 0,
					"shipping": 0,
					"taxes": 12,
					"items": [
						{
							"productId": "1",
							"id": "1",
							"refId": "12",
							"name": "Product Name",
							"price": 100,
							"quantity": 1
						}
					],
					"itemsTotal": 100
				}
			},
			"Item": {
				"title": "Item",
				"required": [
					"productId",
					"id",
					"refId",
					"name",
					"price",
					"quantity"
				],
				"type": "object",
				"properties": {
					"productId": {
						"type": "string"
					},
					"id": {
						"type": "string"
					},
					"refId": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"price": {
						"type": "integer",
						"format": "int32"
					},
					"quantity": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"productId": "1",
					"id": "1",
					"refId": "12",
					"name": "Product Name",
					"price": 100,
					"quantity": 1
				}
			},
			"Client": {
				"title": "Client",
				"required": [
					"id",
					"email",
					"document"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"email": {
						"type": "string"
					},
					"document": {
						"type": "string"
					}
				},
				"example": {
					"id": "019a0cc1-409a-4c16-859b-eefdb81f825e",
					"email": "email@damoain.com",
					"document": "21301923110"
				}
			},
			"response2": {
				"title": "response2",
				"required": [
					"items",
					"paging"
				],
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item1"
						},
						"description": ""
					},
					"paging": {
						"$ref": "#/components/schemas/Paging"
					}
				},
				"example": {
					"items": [
						{
							"id": "589",
							"_self": {
								"href": "cards/589"
							}
						},
						{
							"id": "590",
							"_self": {
								"href": "cards/590"
							}
						},
						{
							"id": "591",
							"_self": {
								"href": "cards/591"
							}
						},
						{
							"id": "592",
							"_self": {
								"href": "cards/592"
							}
						}
					],
					"paging": {
						"page": 0,
						"perPage": 10,
						"total": 4,
						"pages": 1
					}
				}
			},
			"Item1": {
				"title": "Item1",
				"required": [
					"id",
					"_self"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"_self": {
						"$ref": "#/components/schemas/Self"
					}
				},
				"example": {
					"id": "589",
					"_self": {
						"href": "cards/589"
					}
				}
			},
			"Self": {
				"title": "Self",
				"required": [
					"href"
				],
				"type": "object",
				"properties": {
					"href": {
						"type": "string"
					}
				},
				"example": {
					"href": "cards/589"
				}
			},
			"Paging": {
				"title": "Paging",
				"required": [
					"page",
					"perPage",
					"total",
					"pages"
				],
				"type": "object",
				"properties": {
					"page": {
						"type": "integer",
						"format": "int32"
					},
					"perPage": {
						"type": "integer",
						"format": "int32"
					},
					"total": {
						"type": "integer",
						"format": "int32"
					},
					"pages": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"page": 0,
					"perPage": 10,
					"total": 4,
					"pages": 1
				}
			},
			"response3": {
				"title": "response3",
				"required": [
					"id",
					"_self"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"_self": {
						"$ref": "#/components/schemas/Self"
					}
				},
				"example": {
					"id": "268",
					"_self": {
						"href": "cards/890/transactions/268"
					}
				}
			},
			"CreateGiftCardTransactionRequest": {
				"title": "CreateGiftCardTransactionRequest",
				"required": [
					"operation",
					"value",
					"description",
					"redemptionToken",
					"redemptionCode",
					"requestId",
					"orderInfo"
				],
				"type": "object",
				"properties": {
					"operation": {
						"type": "string"
					},
					"value": {
						"type": "integer",
						"format": "int32"
					},
					"description": {
						"type": "string"
					},
					"redemptionToken": {
						"type": "string"
					},
					"redemptionCode": {
						"type": "string"
					},
					"requestId": {
						"type": "string"
					},
					"orderInfo": {
						"$ref": "#/components/schemas/OrderInfo"
					}
				},
				"example": {
					"operation": "Debit",
					"value": 3,
					"description": "GiftCardHub",
					"redemptionToken": "b2dac6f2-f365-48cd-82a9-0b376a55557a",
					"redemptionCode": "",
					"requestId": "B56CBE231DEE4E1A859183C1030CE926",
					"orderInfo": {
						"orderId": "v5006128str",
						"sequence": 5006128,
						"cart": {
							"items": [
								{
									"id": "2001023",
									"productId": "2000492",
									"refId": "35994",
									"name": "Vaporizador Des. Colônia Branco",
									"value": 14.99,
									"price": 14.99,
									"quantity": 1,
									"shippingDiscount": 0,
									"discount": -7.5,
									"priceTags": [
										{
											"name": "discount@price-discount_store_183#4911bf6f-22a2-4af1-a365-cce895c3df2c",
											"value": 0
										}
									]
								}
							],
							"grandTotal": 0,
							"discounts": -7.5,
							"shipping": 7.27,
							"taxes": 0,
							"itemsTotal": 14.99
						},
						"clientProfile": {
							"email": "miguel.scott96@yahoo.com.br",
							"firstName": "miguel",
							"lastName": "scott",
							"document": "02906792063",
							"phone": "+551111111111",
							"birthDate": "0001-01-01T00:00:00",
							"isCorporate": false
						},
						"shipping": {
							"receiverName": "miguel scott",
							"postalCode": "22250040",
							"city": "Rio de Janeiro",
							"state": "RJ",
							"country": "BRA",
							"street": "Praia de Botafogo",
							"number": "111",
							"neighborhood": "Botafogo",
							"complement": null,
							"reference": null
						}
					}
				}
			},
			"OrderInfo": {
				"title": "OrderInfo",
				"required": [
					"orderId",
					"sequence",
					"cart",
					"clientProfile",
					"shipping"
				],
				"type": "object",
				"properties": {
					"orderId": {
						"type": "string"
					},
					"sequence": {
						"type": "integer",
						"format": "int32"
					},
					"cart": {
						"$ref": "#/components/schemas/Cart1"
					},
					"clientProfile": {
						"$ref": "#/components/schemas/ClientProfile"
					},
					"shipping": {
						"$ref": "#/components/schemas/Shipping"
					}
				},
				"example": {
					"orderId": "v5006128str",
					"sequence": 5006128,
					"cart": {
						"items": [
							{
								"id": "2001023",
								"productId": "2000492",
								"refId": "35994",
								"name": "Vaporizador Des. Colônia Branco",
								"value": 14.99,
								"price": 14.99,
								"quantity": 1,
								"shippingDiscount": 0,
								"discount": -7.5,
								"priceTags": [
									{
										"name": "discount@price-discount_store_183#4911bf6f-22a2-4af1-a365-cce895c3df2c",
										"value": 0
									}
								]
							}
						],
						"grandTotal": 0,
						"discounts": -7.5,
						"shipping": 7.27,
						"taxes": 0,
						"itemsTotal": 14.99
					},
					"clientProfile": {
						"email": "miguel.scott96@yahoo.com.br",
						"firstName": "miguel",
						"lastName": "scott",
						"document": "02906792063",
						"phone": "+551111111111",
						"birthDate": "0001-01-01T00:00:00",
						"isCorporate": false
					},
					"shipping": {
						"receiverName": "miguel scott",
						"postalCode": "22250040",
						"city": "Rio de Janeiro",
						"state": "RJ",
						"country": "BRA",
						"street": "Praia de Botafogo",
						"number": "111",
						"neighborhood": "Botafogo",
						"complement": null,
						"reference": null
					}
				}
			},
			"Cart1": {
				"title": "Cart1",
				"required": [
					"items",
					"grandTotal",
					"discounts",
					"shipping",
					"taxes",
					"itemsTotal"
				],
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/Item2"
						},
						"description": ""
					},
					"grandTotal": {
						"type": "integer",
						"format": "int32"
					},
					"discounts": {
						"type": "number"
					},
					"shipping": {
						"type": "number"
					},
					"taxes": {
						"type": "integer",
						"format": "int32"
					},
					"itemsTotal": {
						"type": "number"
					}
				},
				"example": {
					"items": [
						{
							"id": "2001023",
							"productId": "2000492",
							"refId": "35994",
							"name": "Vaporizador Des. Colônia Branco",
							"value": 14.99,
							"price": 14.99,
							"quantity": 1,
							"shippingDiscount": 0,
							"discount": -7.5,
							"priceTags": [
								{
									"name": "discount@price-discount_store_183#4911bf6f-22a2-4af1-a365-cce895c3df2c",
									"value": 0
								}
							]
						}
					],
					"grandTotal": 0,
					"discounts": -7.5,
					"shipping": 7.27,
					"taxes": 0,
					"itemsTotal": 14.99
				}
			},
			"Item2": {
				"title": "Item2",
				"required": [
					"id",
					"productId",
					"refId",
					"name",
					"value",
					"price",
					"quantity",
					"shippingDiscount",
					"discount",
					"priceTags"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"productId": {
						"type": "string"
					},
					"refId": {
						"type": "string"
					},
					"name": {
						"type": "string"
					},
					"value": {
						"type": "number"
					},
					"price": {
						"type": "number"
					},
					"quantity": {
						"type": "integer",
						"format": "int32"
					},
					"shippingDiscount": {
						"type": "integer",
						"format": "int32"
					},
					"discount": {
						"type": "number"
					},
					"priceTags": {
						"type": "array",
						"items": {
							"$ref": "#/components/schemas/PriceTag"
						},
						"description": ""
					}
				},
				"example": {
					"id": "2001023",
					"productId": "2000492",
					"refId": "35994",
					"name": "Vaporizador Des. Colônia Branco",
					"value": 14.99,
					"price": 14.99,
					"quantity": 1,
					"shippingDiscount": 0,
					"discount": -7.5,
					"priceTags": [
						{
							"name": "discount@price-discount_store_183#4911bf6f-22a2-4af1-a365-cce895c3df2c",
							"value": 0
						}
					]
				}
			},
			"PriceTag": {
				"title": "PriceTag",
				"required": [
					"name",
					"value"
				],
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"value": {
						"type": "integer",
						"format": "int32"
					}
				},
				"example": {
					"name": "discount@price-discount_store_183#4911bf6f-22a2-4af1-a365-cce895c3df2c",
					"value": 0
				}
			},
			"ClientProfile": {
				"title": "ClientProfile",
				"required": [
					"email",
					"firstName",
					"lastName",
					"document",
					"phone",
					"birthDate",
					"isCorporate"
				],
				"type": "object",
				"properties": {
					"email": {
						"type": "string"
					},
					"firstName": {
						"type": "string"
					},
					"lastName": {
						"type": "string"
					},
					"document": {
						"type": "string"
					},
					"phone": {
						"type": "string"
					},
					"birthDate": {
						"type": "string"
					},
					"isCorporate": {
						"type": "boolean"
					}
				},
				"example": {
					"email": "miguel.scott96@yahoo.com.br",
					"firstName": "miguel",
					"lastName": "scott",
					"document": "02906792063",
					"phone": "+551111111111",
					"birthDate": "0001-01-01T00:00:00",
					"isCorporate": false
				}
			},
			"Shipping": {
				"title": "Shipping",
				"required": [
					"receiverName",
					"postalCode",
					"city",
					"state",
					"country",
					"street",
					"number",
					"neighborhood",
					"complement",
					"reference"
				],
				"type": "object",
				"properties": {
					"receiverName": {
						"type": "string"
					},
					"postalCode": {
						"type": "string"
					},
					"city": {
						"type": "string"
					},
					"state": {
						"type": "string"
					},
					"country": {
						"type": "string"
					},
					"street": {
						"type": "string"
					},
					"number": {
						"type": "string"
					},
					"neighborhood": {
						"type": "string"
					},
					"complement": {
						"type": "string",
						"nullable": true
					},
					"reference": {
						"type": "string",
						"nullable": true
					}
				},
				"example": {
					"receiverName": "miguel scott",
					"postalCode": "22250040",
					"city": "Rio de Janeiro",
					"state": "RJ",
					"country": "BRA",
					"street": "Praia de Botafogo",
					"number": "111",
					"neighborhood": "Botafogo",
					"complement": null,
					"reference": null
				}
			},
			"response5": {
				"title": "response5",
				"required": [
					"value",
					"description",
					"date",
					"redemptionMode"
				],
				"type": "object",
				"properties": {
					"value": {
						"type": "number"
					},
					"description": {
						"type": "string"
					},
					"date": {
						"type": "string"
					},
					"redemptionMode": {
						"type": "string"
					}
				},
				"example": {
					"value": 123.4,
					"description": "Crédito relacionado a compra 10281230-01",
					"date": "2016-01-01T00:00:00",
					"redemptionMode": "redemptionToken"
				}
			},
			"response6": {
				"title": "response6",
				"required": [
					"oid",
					"value",
					"date"
				],
				"type": "object",
				"properties": {
					"oid": {
						"type": "string"
					},
					"value": {
						"type": "number"
					},
					"date": {
						"type": "string"
					}
				},
				"example": {
					"oid": "7cf8d7970e1c81d05620e46cceb6819f",
					"value": 123.4,
					"date": "2016-01-01T00:00:00"
				}
			},
			"response7": {
				"title": "response7",
				"required": [
					"id",
					"value",
					"date"
				],
				"type": "object",
				"properties": {
					"id": {
						"type": "string"
					},
					"value": {
						"type": "number"
					},
					"date": {
						"type": "string"
					}
				},
				"example": {
					"id": "239d35b430fc75379db966c1d3670c6f",
					"value": 13.4,
					"date": "2016-04-06T00:00:00"
				}
			},
			"CancelGiftCardTransactionRequest": {
				"title": "CancelGiftCardTransactionRequest",
				"required": [
					"value",
					"requestId"
				],
				"type": "object",
				"properties": {
					"value": {
						"type": "number"
					},
					"requestId": {
						"type": "string"
					}
				},
				"example": {
					"value": 13,
					"requestId": "6360f98eb0cf6fd5afa77e39bba8c20fe5807d8c"
				}
			},
			"SettleGiftCardTransactionRequest": {
				"title": "SettleGiftCardTransactionRequest",
				"required": [
					"value",
					"requestId"
				],
				"type": "object",
				"properties": {
					"value": {
						"type": "number"
					},
					"requestId": {
						"type": "string"
					}
				},
				"example": {
					"value": 17.4,
					"requestId": "6360f98eb0cf6fd5afa77e39bba8c20fe5807d8c"
				}
			}
		},
		"securitySchemes": {
			"appKey": {
				"type": "apiKey",
				"in": "header",
				"name": "X-VTEX-API-AppKey"
			},
			"appToken": {
				"type": "apiKey",
				"in": "header",
				"name": "X-VTEX-API-AppToken"
			}
		}
	},
	"tags": [
		{
			"name": "Miscellaneous",
			"description": ""
		}
	],
	"security": [
		{
			"appKey": [],
			"appToken": []
		}
	]
}